name: flutter_whip_example_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_icons: ^1.0.0
  flutter_whip:
    path: ../
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.0.5
  #picture_in_picture:
  simple_pip_mode: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true