name: flutter_whip
version: 0.5.4
description: WebRTC-HTTP ingestion protocol (WHIP) library for flutter.
homepage: https://github.com/cloudwebrtc/flutter-whip.git
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  events2: ^1.0.0
  flutter_webrtc:
    git: 
      url: https://github.com/lambiengcode/flutter-webrtc-for-pip.git
      path: '.'
      ref: 'main'
  http: ^0.13.3
  sdp_transform: ^0.3.2
  uuid: ^3.0.3 
  web_socket_channel: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  test: ^1.6.7
